
import { BakeryItem } from './types';

// Note: User authentication is now handled via Supabase 'users' table
// See supabase_users_table.sql for the table schema and initial user data


export const INITIAL_ITEMS: BakeryItem[] = [
  // ============ BEVERAGES ============
  { id: '1', name: 'COKE LIT.', category: 'Beverage', unit: 'btl', costPrice: 30, sellingPrice: 45 },
  { id: '2', name: 'COKE KASALO', category: 'Beverage', unit: 'btl', costPrice: 25, sellingPrice: 35 },
  { id: '3', name: 'COKE OZ', category: 'Beverage', unit: 'btl', costPrice: 10, sellingPrice: 15 },
  { id: '4', name: 'MINERAL 350ML', category: 'Beverage', unit: 'btl', costPrice: 7, sellingPrice: 10 },
  { id: '5', name: 'MINERAL 500ML', category: 'Beverage', unit: 'btl', costPrice: 10, sellingPrice: 15 },
  { id: '6', name: 'MINERAL 1LT', category: 'Beverage', unit: 'btl', costPrice: 18, sellingPrice: 25 },
  { id: '7', name: 'COBRA PLASTIC', category: 'Beverage', unit: 'btl', costPrice: 18, sellingPrice: 25 },
  { id: '8', name: 'COBRA BOTTLE', category: 'Beverage', unit: 'btl', costPrice: 15, sellingPrice: 20 },
  { id: '9', name: 'STING', category: 'Beverage', unit: 'btl', costPrice: 18, sellingPrice: 25 },
  { id: '10', name: 'GATORADE', category: 'Beverage', unit: 'btl', costPrice: 30, sellingPrice: 40 },
  { id: '11', name: 'C2 BIG', category: 'Beverage', unit: 'btl', costPrice: 22, sellingPrice: 30 },
  { id: '12', name: 'C2 SOLO', category: 'Beverage', unit: 'btl', costPrice: 12, sellingPrice: 17 },
  { id: '13', name: 'KALAMANSI JUICE', category: 'Beverage', unit: 'cup', costPrice: 18, sellingPrice: 25 },

  // ============ COFFEES ============
  { id: '14', name: 'MILO', category: 'Coffee', unit: 'sachet', costPrice: 8, sellingPrice: 12 },
  { id: '15', name: 'SWAK', category: 'Coffee', unit: 'sachet', costPrice: 10, sellingPrice: 15 },
  { id: '16', name: 'BIRCH TREE', category: 'Coffee', unit: 'sachet', costPrice: 10, sellingPrice: 15 },
  { id: '17', name: 'COFFEE MATE', category: 'Coffee', unit: 'sachet', costPrice: 3, sellingPrice: 4 },
  { id: '18', name: 'CREAM ALL', category: 'Coffee', unit: 'sachet', costPrice: 3, sellingPrice: 4 },
  { id: '19', name: 'NESCAFE STICK', category: 'Coffee', unit: 'sachet', costPrice: 3, sellingPrice: 4 },
  { id: '20', name: 'PREMIUM', category: 'Coffee', unit: 'sachet', costPrice: 3, sellingPrice: 4 },
  { id: '21', name: '3N1 (SINGLE)', category: 'Coffee', unit: 'sachet', costPrice: 7, sellingPrice: 10 },
  { id: '22', name: '3N1 (TWIN)', category: 'Coffee', unit: 'sachet', costPrice: 10, sellingPrice: 15 },
  { id: '23', name: 'CHAMPION TWIN', category: 'Coffee', unit: 'sachet', costPrice: 12, sellingPrice: 17 },
  { id: '24', name: 'CREAMY WHITE & LATTE (TWIN)', category: 'Coffee', unit: 'sachet', costPrice: 11, sellingPrice: 16 },
  { id: '25', name: 'KOPIKO L.A', category: 'Coffee', unit: 'sachet', costPrice: 7, sellingPrice: 10 },

  // ============ BREAD ============
  { id: '26', name: 'CHIFFON SLICE', category: 'Bread', unit: 'pcs', costPrice: 15, sellingPrice: 20 },
  { id: '27', name: 'CHIFFON (LARGE)', category: 'Bread', unit: 'pcs', costPrice: 180, sellingPrice: 250 },
  { id: '28', name: 'CHIFFON (SMALL)', category: 'Bread', unit: 'pcs', costPrice: 110, sellingPrice: 150 },
  { id: '29', name: 'BROWNIES', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '30', name: 'SWEETHEART', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '31', name: 'CRINKLES', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '32', name: 'RIBBON', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '33', name: 'HALFMOON', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '34', name: 'TORTA', category: 'Bread', unit: 'pcs', costPrice: 10, sellingPrice: 15 },
  { id: '35', name: 'MAMON', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '36', name: 'HOPIA', category: 'Bread', unit: 'pcs', costPrice: 5, sellingPrice: 7 },
  { id: '37', name: 'CINAMON (SLICE)', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '38', name: 'SQUASH', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '39', name: 'UBE', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '40', name: 'ENSAYMADA', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '41', name: 'ENSAYMADA (BIG)', category: 'Bread', unit: 'pcs', costPrice: 15, sellingPrice: 20 },
  { id: '42', name: 'PAN DE SIOSA', category: 'Bread', unit: 'pcs', costPrice: 22, sellingPrice: 30 },
  { id: '43', name: 'CINAMON LOAF', category: 'Bread', unit: 'pcs', costPrice: 30, sellingPrice: 40 },
  { id: '44', name: 'CINAMON ROLL', category: 'Bread', unit: 'pcs', costPrice: 7, sellingPrice: 10 },
  { id: '45', name: 'MARBLE LOAF', category: 'Bread', unit: 'pcs', costPrice: 33, sellingPrice: 45 },
  { id: '46', name: 'LOAF BREAD (LARGE)', category: 'Bread', unit: 'loaf', costPrice: 45, sellingPrice: 60 },
  { id: '47', name: 'LOAF BREAD (SMALL)', category: 'Bread', unit: 'loaf', costPrice: 18, sellingPrice: 25 },
  { id: '48', name: 'BURGER BUNS', category: 'Bread', unit: 'pcs', costPrice: 18, sellingPrice: 25 },
  { id: '49', name: 'FIG PIE', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '50', name: 'MONGGO', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '51', name: 'PAN DE COCO', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '52', name: 'GERMAN', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '53', name: 'SPANISH', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '54', name: 'CHOCO LANAY', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '55', name: 'ATIS', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '56', name: 'HALFBREAD', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '57', name: 'MONAY', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '58', name: 'STAR BREAD', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '59', name: 'POTOK', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '60', name: 'CHEESE DESAL', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '61', name: 'EGG BREAD', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '62', name: 'PAN DE LECHE (5PCS)', category: 'Bread', unit: 'pack', costPrice: 15, sellingPrice: 20 },
  { id: '63', name: 'PUDING', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '64', name: 'CHOCO RING', category: 'Bread', unit: 'pcs', costPrice: 7, sellingPrice: 10 },
  { id: '65', name: 'CUSTARD CAKE', category: 'Bread', unit: 'pcs', costPrice: 15, sellingPrice: 20 },
  { id: '66', name: 'CHEESE BREAD', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '67', name: 'PANDESAL', category: 'Bread', unit: 'pcs', costPrice: 1.5, sellingPrice: 2 },
  { id: '68', name: 'CELEB. CAKE (SMALL)', category: 'Bread', unit: 'pcs', costPrice: 450, sellingPrice: 600 },
  { id: '69', name: 'CELEB. CAKE (LARGE)', category: 'Bread', unit: 'pcs', costPrice: 900, sellingPrice: 1200 },
  { id: '70', name: 'MOIST CAKE', category: 'Bread', unit: 'pcs', costPrice: 600, sellingPrice: 800 },
  { id: '71', name: 'BANANA CAKE', category: 'Bread', unit: 'pcs', costPrice: 4, sellingPrice: 6 },
  { id: '72', name: 'PINEAPPLE PIE', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '73', name: 'JELLY ROLL', category: 'Bread', unit: 'pcs', costPrice: 15, sellingPrice: 20 },
  { id: '74', name: 'SALYOT BREAD', category: 'Bread', unit: 'pcs', costPrice: 3, sellingPrice: 5 },
  { id: '75', name: 'MUFFINS', category: 'Bread', unit: 'pcs', costPrice: 7, sellingPrice: 10 },
  { id: '76', name: 'MUFFINS W/ICING', category: 'Bread', unit: 'pcs', costPrice: 10, sellingPrice: 15 },
  { id: '77', name: 'SLICE CAKE', category: 'Bread', unit: 'pcs', costPrice: 22, sellingPrice: 30 },
];

export const APP_COLORS = {
  primary: 'amber-800',
  secondary: 'amber-100',
  accent: 'orange-500',
  background: 'stone-50',
};
